// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StudyCycleCLI.Model;

#nullable disable

namespace StudyCycleCLI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250513131020_ConnectionBetweenTablesEntities")]
    partial class ConnectionBetweenTablesEntities
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.4");

            modelBuilder.Entity("StudyCycleCLI.Model.StudyCycle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CompletedTimes")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<double>("DailyStudyHours")
                        .HasColumnType("REAL");

                    b.Property<int>("FactorOne")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FactorThree")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FactorTwo")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastStudiedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<double>("WeeklyStudyHours")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("StudyCycles");
                });

            modelBuilder.Entity("StudyCycleCLI.Model.StudyCycleSubject", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AmountOfContent")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CompletedTimes")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Difficulty")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastStudiedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("MaxStudyHours")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StudiedHours")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StudyCycleId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<double>("Weight")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("StudyCycleId");

                    b.ToTable("StudyCycleSubjects");
                });

            modelBuilder.Entity("StudyCycleCLI.Model.StudyCycleSubject", b =>
                {
                    b.HasOne("StudyCycleCLI.Model.StudyCycle", "StudyCycle")
                        .WithMany("Subjects")
                        .HasForeignKey("StudyCycleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("StudyCycle");
                });

            modelBuilder.Entity("StudyCycleCLI.Model.StudyCycle", b =>
                {
                    b.Navigation("Subjects");
                });
#pragma warning restore 612, 618
        }
    }
}
